export CUDA_VISIBLE_DEVICES=5
python debias/unbiased_model.py --constraint_loss_weight 0.001 --claim_loss_weight 0.1
python debias/unbiased_model.py --constraint_loss_weight 0.002 --claim_loss_weight 0.1
python debias/unbiased_model.py --constraint_loss_weight 0.003 --claim_loss_weight 0.1
python debias/unbiased_model.py --constraint_loss_weight 0.004 --claim_loss_weight 0.1
python debias/unbiased_model.py --constraint_loss_weight 0.005 --claim_loss_weight 0.1
python debias/unbiased_model.py --constraint_loss_weight 0.006 --claim_loss_weight 0.1
python debias/unbiased_model.py --constraint_loss_weight 0.007 --claim_loss_weight 0.1
python debias/unbiased_model.py --constraint_loss_weight 0.008 --claim_loss_weight 0.1
python debias/unbiased_model.py --constraint_loss_weight 0.009 --claim_loss_weight 0.1
python debias/unbiased_model.py --constraint_loss_weight 0.01 --claim_loss_weight 0.1
python debias/unbiased_model.py --constraint_loss_weight 0.001 --claim_loss_weight 0.2
python debias/unbiased_model.py --constraint_loss_weight 0.002 --claim_loss_weight 0.2
python debias/unbiased_model.py --constraint_loss_weight 0.003 --claim_loss_weight 0.2
python debias/unbiased_model.py --constraint_loss_weight 0.004 --claim_loss_weight 0.2
python debias/unbiased_model.py --constraint_loss_weight 0.005 --claim_loss_weight 0.2
python debias/unbiased_model.py --constraint_loss_weight 0.006 --claim_loss_weight 0.2
python debias/unbiased_model.py --constraint_loss_weight 0.007 --claim_loss_weight 0.2
python debias/unbiased_model.py --constraint_loss_weight 0.008 --claim_loss_weight 0.2
python debias/unbiased_model.py --constraint_loss_weight 0.009 --claim_loss_weight 0.2
python debias/unbiased_model.py --constraint_loss_weight 0.010 --claim_loss_weight 0.2
python debias/unbiased_model.py --constraint_loss_weight 0.001 --claim_loss_weight 0.3
python debias/unbiased_model.py --constraint_loss_weight 0.002 --claim_loss_weight 0.3
python debias/unbiased_model.py --constraint_loss_weight 0.003 --claim_loss_weight 0.3
python debias/unbiased_model.py --constraint_loss_weight 0.004 --claim_loss_weight 0.3
python debias/unbiased_model.py --constraint_loss_weight 0.005 --claim_loss_weight 0.3
python debias/unbiased_model.py --constraint_loss_weight 0.006 --claim_loss_weight 0.3
python debias/unbiased_model.py --constraint_loss_weight 0.007 --claim_loss_weight 0.3
python debias/unbiased_model.py --constraint_loss_weight 0.008 --claim_loss_weight 0.3
python debias/unbiased_model.py --constraint_loss_weight 0.009 --claim_loss_weight 0.3
python debias/unbiased_model.py --constraint_loss_weight 0.010 --claim_loss_weight 0.3
python debias/unbiased_model.py --constraint_loss_weight 0.001 --claim_loss_weight 0.4
python debias/unbiased_model.py --constraint_loss_weight 0.002 --claim_loss_weight 0.4
python debias/unbiased_model.py --constraint_loss_weight 0.003 --claim_loss_weight 0.4
python debias/unbiased_model.py --constraint_loss_weight 0.004 --claim_loss_weight 0.4
python debias/unbiased_model.py --constraint_loss_weight 0.005 --claim_loss_weight 0.4
python debias/unbiased_model.py --constraint_loss_weight 0.006 --claim_loss_weight 0.4
python debias/unbiased_model.py --constraint_loss_weight 0.007 --claim_loss_weight 0.4
python debias/unbiased_model.py --constraint_loss_weight 0.008 --claim_loss_weight 0.4
python debias/unbiased_model.py --constraint_loss_weight 0.009 --claim_loss_weight 0.4
python debias/unbiased_model.py --constraint_loss_weight 0.010 --claim_loss_weight 0.4
python debias/unbiased_model.py --constraint_loss_weight 0.001 --claim_loss_weight 0.5
python debias/unbiased_model.py --constraint_loss_weight 0.002 --claim_loss_weight 0.5
python debias/unbiased_model.py --constraint_loss_weight 0.003 --claim_loss_weight 0.5
python debias/unbiased_model.py --constraint_loss_weight 0.004 --claim_loss_weight 0.5
python debias/unbiased_model.py --constraint_loss_weight 0.005 --claim_loss_weight 0.5
python debias/unbiased_model.py --constraint_loss_weight 0.006 --claim_loss_weight 0.5
python debias/unbiased_model.py --constraint_loss_weight 0.007 --claim_loss_weight 0.5
python debias/unbiased_model.py --constraint_loss_weight 0.008 --claim_loss_weight 0.5
python debias/unbiased_model.py --constraint_loss_weight 0.009 --claim_loss_weight 0.5
python debias/unbiased_model.py --constraint_loss_weight 0.010 --claim_loss_weight 0.5