export CUDA_VISIBLE_DEVICES=4
python debias/unbiased_model2.py --constraint_loss_weight 0.003 --claim_loss_weight 0.0
python debias/unbiased_model2.py --constraint_loss_weight 0.003 --claim_loss_weight 0.1
python debias/unbiased_model2.py --constraint_loss_weight 0.003 --claim_loss_weight 0.2
python debias/unbiased_model2.py --constraint_loss_weight 0.003 --claim_loss_weight 0.3
python debias/unbiased_model2.py --constraint_loss_weight 0.003 --claim_loss_weight 0.4
python debias/unbiased_model2.py --constraint_loss_weight 0.003 --claim_loss_weight 0.5
python debias/unbiased_model2.py --constraint_loss_weight 0.003 --claim_loss_weight 0.6
python debias/unbiased_model2.py --constraint_loss_weight 0.003 --claim_loss_weight 0.7
python debias/unbiased_model2.py --constraint_loss_weight 0.003 --claim_loss_weight 0.8
python debias/unbiased_model2.py --constraint_loss_weight 0.003 --claim_loss_weight 0.9
python debias/unbiased_model2.py --constraint_loss_weight 0.006 --claim_loss_weight 1.0
python debias/unbiased_model2.py --constraint_loss_weight 0.006 --claim_loss_weight 0.0
python debias/unbiased_model2.py --constraint_loss_weight 0.006 --claim_loss_weight 0.1
python debias/unbiased_model2.py --constraint_loss_weight 0.006 --claim_loss_weight 0.2
python debias/unbiased_model2.py --constraint_loss_weight 0.006 --claim_loss_weight 0.3
python debias/unbiased_model2.py --constraint_loss_weight 0.006 --claim_loss_weight 0.4
python debias/unbiased_model2.py --constraint_loss_weight 0.006 --claim_loss_weight 0.5
python debias/unbiased_model2.py --constraint_loss_weight 0.006 --claim_loss_weight 0.6
python debias/unbiased_model2.py --constraint_loss_weight 0.006 --claim_loss_weight 0.7
python debias/unbiased_model2.py --constraint_loss_weight 0.006 --claim_loss_weight 0.8
python debias/unbiased_model2.py --constraint_loss_weight 0.006 --claim_loss_weight 0.9
python debias/unbiased_model2.py --constraint_loss_weight 0.006 --claim_loss_weight 1.0