export CUDA_VISIBLE_DEVICES=3
python debias/unbiased_model.py --constraint_loss_weight 0.001 --claim_loss_weight 0.6
python debias/unbiased_model.py --constraint_loss_weight 0.002 --claim_loss_weight 0.6
python debias/unbiased_model.py --constraint_loss_weight 0.003 --claim_loss_weight 0.6
python debias/unbiased_model.py --constraint_loss_weight 0.004 --claim_loss_weight 0.6
python debias/unbiased_model.py --constraint_loss_weight 0.005 --claim_loss_weight 0.6
python debias/unbiased_model.py --constraint_loss_weight 0.006 --claim_loss_weight 0.6
python debias/unbiased_model.py --constraint_loss_weight 0.007 --claim_loss_weight 0.6
python debias/unbiased_model.py --constraint_loss_weight 0.008 --claim_loss_weight 0.6
python debias/unbiased_model.py --constraint_loss_weight 0.009 --claim_loss_weight 0.6
python debias/unbiased_model.py --constraint_loss_weight 0.010 --claim_loss_weight 0.6
python debias/unbiased_model.py --constraint_loss_weight 0.001 --claim_loss_weight 0.7
python debias/unbiased_model.py --constraint_loss_weight 0.002 --claim_loss_weight 0.7
python debias/unbiased_model.py --constraint_loss_weight 0.003 --claim_loss_weight 0.7
python debias/unbiased_model.py --constraint_loss_weight 0.004 --claim_loss_weight 0.7
python debias/unbiased_model.py --constraint_loss_weight 0.005 --claim_loss_weight 0.7
python debias/unbiased_model.py --constraint_loss_weight 0.006 --claim_loss_weight 0.7
python debias/unbiased_model.py --constraint_loss_weight 0.007 --claim_loss_weight 0.7
python debias/unbiased_model.py --constraint_loss_weight 0.008 --claim_loss_weight 0.7
python debias/unbiased_model.py --constraint_loss_weight 0.009 --claim_loss_weight 0.7
python debias/unbiased_model.py --constraint_loss_weight 0.010 --claim_loss_weight 0.7
python debias/unbiased_model.py --constraint_loss_weight 0.001 --claim_loss_weight 0.8
python debias/unbiased_model.py --constraint_loss_weight 0.002 --claim_loss_weight 0.8
python debias/unbiased_model.py --constraint_loss_weight 0.003 --claim_loss_weight 0.8
python debias/unbiased_model.py --constraint_loss_weight 0.004 --claim_loss_weight 0.8
python debias/unbiased_model.py --constraint_loss_weight 0.005 --claim_loss_weight 0.8
python debias/unbiased_model.py --constraint_loss_weight 0.006 --claim_loss_weight 0.8
python debias/unbiased_model.py --constraint_loss_weight 0.007 --claim_loss_weight 0.8
python debias/unbiased_model.py --constraint_loss_weight 0.008 --claim_loss_weight 0.8
python debias/unbiased_model.py --constraint_loss_weight 0.009 --claim_loss_weight 0.8
python debias/unbiased_model.py --constraint_loss_weight 0.010 --claim_loss_weight 0.8
python debias/unbiased_model.py --constraint_loss_weight 0.001 --claim_loss_weight 0.9
python debias/unbiased_model.py --constraint_loss_weight 0.002 --claim_loss_weight 0.9
python debias/unbiased_model.py --constraint_loss_weight 0.003 --claim_loss_weight 0.9
python debias/unbiased_model.py --constraint_loss_weight 0.004 --claim_loss_weight 0.9
python debias/unbiased_model.py --constraint_loss_weight 0.005 --claim_loss_weight 0.9
python debias/unbiased_model.py --constraint_loss_weight 0.006 --claim_loss_weight 0.9
python debias/unbiased_model.py --constraint_loss_weight 0.007 --claim_loss_weight 0.9
python debias/unbiased_model.py --constraint_loss_weight 0.008 --claim_loss_weight 0.9
python debias/unbiased_model.py --constraint_loss_weight 0.009 --claim_loss_weight 0.9
python debias/unbiased_model.py --constraint_loss_weight 0.010 --claim_loss_weight 0.9
python debias/unbiased_model.py --constraint_loss_weight 0.001 --claim_loss_weight 1.0
python debias/unbiased_model.py --constraint_loss_weight 0.002 --claim_loss_weight 1.0
python debias/unbiased_model.py --constraint_loss_weight 0.003 --claim_loss_weight 1.0
python debias/unbiased_model.py --constraint_loss_weight 0.004 --claim_loss_weight 1.0
python debias/unbiased_model.py --constraint_loss_weight 0.005 --claim_loss_weight 1.0
python debias/unbiased_model.py --constraint_loss_weight 0.006 --claim_loss_weight 1.0
python debias/unbiased_model.py --constraint_loss_weight 0.007 --claim_loss_weight 1.0
python debias/unbiased_model.py --constraint_loss_weight 0.008 --claim_loss_weight 1.0
python debias/unbiased_model.py --constraint_loss_weight 0.009 --claim_loss_weight 1.0
python debias/unbiased_model.py --constraint_loss_weight 0.010 --claim_loss_weight 1.0