export CUDA_VISIBLE_DEVICES=5
python politihop_scripts/dual_debiased_model_adversarial.py --constraint_loss_weight 0.0 --claim_loss_weight 0.0
python politihop_scripts/dual_debiased_model_adversarial.py --constraint_loss_weight 0.0 --claim_loss_weight 0.1
python politihop_scripts/dual_debiased_model_adversarial.py --constraint_loss_weight 0.0 --claim_loss_weight 0.2
python politihop_scripts/dual_debiased_model_adversarial.py --constraint_loss_weight 0.0 --claim_loss_weight 0.3
python politihop_scripts/dual_debiased_model_adversarial.py --constraint_loss_weight 0.0 --claim_loss_weight 0.4
python politihop_scripts/dual_debiased_model_adversarial.py --constraint_loss_weight 0.0 --claim_loss_weight 0.5
python politihop_scripts/dual_debiased_model_adversarial.py --constraint_loss_weight 0.0 --claim_loss_weight 0.6
python politihop_scripts/dual_debiased_model_adversarial.py --constraint_loss_weight 0.0 --claim_loss_weight 0.7
python politihop_scripts/dual_debiased_model_adversarial.py --constraint_loss_weight 0.0 --claim_loss_weight 0.8
python politihop_scripts/dual_debiased_model_adversarial.py --constraint_loss_weight 0.0 --claim_loss_weight 0.9
python politihop_scripts/dual_debiased_model_adversarial.py --constraint_loss_weight 0.001 --claim_loss_weight 0.0
python politihop_scripts/dual_debiased_model_adversarial.py --constraint_loss_weight 0.001 --claim_loss_weight 0.1
python politihop_scripts/dual_debiased_model_adversarial.py --constraint_loss_weight 0.001 --claim_loss_weight 0.2
python politihop_scripts/dual_debiased_model_adversarial.py --constraint_loss_weight 0.001 --claim_loss_weight 0.3
python politihop_scripts/dual_debiased_model_adversarial.py --constraint_loss_weight 0.001 --claim_loss_weight 0.4
python politihop_scripts/dual_debiased_model_adversarial.py --constraint_loss_weight 0.001 --claim_loss_weight 0.5
python politihop_scripts/dual_debiased_model_adversarial.py --constraint_loss_weight 0.001 --claim_loss_weight 0.6
python politihop_scripts/dual_debiased_model_adversarial.py --constraint_loss_weight 0.001 --claim_loss_weight 0.7
python politihop_scripts/dual_debiased_model_adversarial.py --constraint_loss_weight 0.001 --claim_loss_weight 0.8
python politihop_scripts/dual_debiased_model_adversarial.py --constraint_loss_weight 0.001 --claim_loss_weight 0.9
python politihop_scripts/dual_debiased_model_adversarial.py --constraint_loss_weight 0.002 --claim_loss_weight 0.0
python politihop_scripts/dual_debiased_model_adversarial.py --constraint_loss_weight 0.002 --claim_loss_weight 0.1
python politihop_scripts/dual_debiased_model_adversarial.py --constraint_loss_weight 0.002 --claim_loss_weight 0.2
python politihop_scripts/dual_debiased_model_adversarial.py --constraint_loss_weight 0.002 --claim_loss_weight 0.3
python politihop_scripts/dual_debiased_model_adversarial.py --constraint_loss_weight 0.002 --claim_loss_weight 0.4
python politihop_scripts/dual_debiased_model_adversarial.py --constraint_loss_weight 0.002 --claim_loss_weight 0.5
python politihop_scripts/dual_debiased_model_adversarial.py --constraint_loss_weight 0.002 --claim_loss_weight 0.6
python politihop_scripts/dual_debiased_model_adversarial.py --constraint_loss_weight 0.002 --claim_loss_weight 0.7
python politihop_scripts/dual_debiased_model_adversarial.py --constraint_loss_weight 0.002 --claim_loss_weight 0.8
python politihop_scripts/dual_debiased_model_adversarial.py --constraint_loss_weight 0.002 --claim_loss_weight 0.9
python politihop_scripts/dual_debiased_model_adversarial.py --constraint_loss_weight 0.003 --claim_loss_weight 0.0
python politihop_scripts/dual_debiased_model_adversarial.py --constraint_loss_weight 0.003 --claim_loss_weight 0.1
python politihop_scripts/dual_debiased_model_adversarial.py --constraint_loss_weight 0.003 --claim_loss_weight 0.2
python politihop_scripts/dual_debiased_model_adversarial.py --constraint_loss_weight 0.003 --claim_loss_weight 0.3
python politihop_scripts/dual_debiased_model_adversarial.py --constraint_loss_weight 0.003 --claim_loss_weight 0.4
python politihop_scripts/dual_debiased_model_adversarial.py --constraint_loss_weight 0.003 --claim_loss_weight 0.5
python politihop_scripts/dual_debiased_model_adversarial.py --constraint_loss_weight 0.003 --claim_loss_weight 0.6
python politihop_scripts/dual_debiased_model_adversarial.py --constraint_loss_weight 0.003 --claim_loss_weight 0.7
python politihop_scripts/dual_debiased_model_adversarial.py --constraint_loss_weight 0.003 --claim_loss_weight 0.8
python politihop_scripts/dual_debiased_model_adversarial.py --constraint_loss_weight 0.003 --claim_loss_weight 0.9
python politihop_scripts/dual_debiased_model_adversarial.py --constraint_loss_weight 0.004 --claim_loss_weight 0.0
python politihop_scripts/dual_debiased_model_adversarial.py --constraint_loss_weight 0.004 --claim_loss_weight 0.1
python politihop_scripts/dual_debiased_model_adversarial.py --constraint_loss_weight 0.004 --claim_loss_weight 0.2
python politihop_scripts/dual_debiased_model_adversarial.py --constraint_loss_weight 0.004 --claim_loss_weight 0.3
python politihop_scripts/dual_debiased_model_adversarial.py --constraint_loss_weight 0.004 --claim_loss_weight 0.4
python politihop_scripts/dual_debiased_model_adversarial.py --constraint_loss_weight 0.004 --claim_loss_weight 0.5
python politihop_scripts/dual_debiased_model_adversarial.py --constraint_loss_weight 0.004 --claim_loss_weight 0.6
python politihop_scripts/dual_debiased_model_adversarial.py --constraint_loss_weight 0.004 --claim_loss_weight 0.7
python politihop_scripts/dual_debiased_model_adversarial.py --constraint_loss_weight 0.004 --claim_loss_weight 0.8
python politihop_scripts/dual_debiased_model_adversarial.py --constraint_loss_weight 0.004 --claim_loss_weight 0.9
python politihop_scripts/dual_debiased_model_adversarial.py --constraint_loss_weight 0.005 --claim_loss_weight 0.0
python politihop_scripts/dual_debiased_model_adversarial.py --constraint_loss_weight 0.005 --claim_loss_weight 0.1
python politihop_scripts/dual_debiased_model_adversarial.py --constraint_loss_weight 0.005 --claim_loss_weight 0.2
python politihop_scripts/dual_debiased_model_adversarial.py --constraint_loss_weight 0.005 --claim_loss_weight 0.3
python politihop_scripts/dual_debiased_model_adversarial.py --constraint_loss_weight 0.005 --claim_loss_weight 0.4
python politihop_scripts/dual_debiased_model_adversarial.py --constraint_loss_weight 0.005 --claim_loss_weight 0.5
python politihop_scripts/dual_debiased_model_adversarial.py --constraint_loss_weight 0.005 --claim_loss_weight 0.6
python politihop_scripts/dual_debiased_model_adversarial.py --constraint_loss_weight 0.005 --claim_loss_weight 0.7
python politihop_scripts/dual_debiased_model_adversarial.py --constraint_loss_weight 0.005 --claim_loss_weight 0.8
python politihop_scripts/dual_debiased_model_adversarial.py --constraint_loss_weight 0.005 --claim_loss_weight 0.9
python politihop_scripts/dual_debiased_model_adversarial.py --constraint_loss_weight 0.006 --claim_loss_weight 0.0
python politihop_scripts/dual_debiased_model_adversarial.py --constraint_loss_weight 0.006 --claim_loss_weight 0.1
python politihop_scripts/dual_debiased_model_adversarial.py --constraint_loss_weight 0.006 --claim_loss_weight 0.2
python politihop_scripts/dual_debiased_model_adversarial.py --constraint_loss_weight 0.006 --claim_loss_weight 0.3
python politihop_scripts/dual_debiased_model_adversarial.py --constraint_loss_weight 0.006 --claim_loss_weight 0.4
python politihop_scripts/dual_debiased_model_adversarial.py --constraint_loss_weight 0.006 --claim_loss_weight 0.5
python politihop_scripts/dual_debiased_model_adversarial.py --constraint_loss_weight 0.006 --claim_loss_weight 0.6
python politihop_scripts/dual_debiased_model_adversarial.py --constraint_loss_weight 0.006 --claim_loss_weight 0.7
python politihop_scripts/dual_debiased_model_adversarial.py --constraint_loss_weight 0.006 --claim_loss_weight 0.8
python politihop_scripts/dual_debiased_model_adversarial.py --constraint_loss_weight 0.006 --claim_loss_weight 0.9
python politihop_scripts/dual_debiased_model_adversarial.py --constraint_loss_weight 0.007 --claim_loss_weight 0.0
python politihop_scripts/dual_debiased_model_adversarial.py --constraint_loss_weight 0.007 --claim_loss_weight 0.1
python politihop_scripts/dual_debiased_model_adversarial.py --constraint_loss_weight 0.007 --claim_loss_weight 0.2
python politihop_scripts/dual_debiased_model_adversarial.py --constraint_loss_weight 0.007 --claim_loss_weight 0.3
python politihop_scripts/dual_debiased_model_adversarial.py --constraint_loss_weight 0.007 --claim_loss_weight 0.4
python politihop_scripts/dual_debiased_model_adversarial.py --constraint_loss_weight 0.007 --claim_loss_weight 0.5
python politihop_scripts/dual_debiased_model_adversarial.py --constraint_loss_weight 0.007 --claim_loss_weight 0.6
python politihop_scripts/dual_debiased_model_adversarial.py --constraint_loss_weight 0.007 --claim_loss_weight 0.7
python politihop_scripts/dual_debiased_model_adversarial.py --constraint_loss_weight 0.007 --claim_loss_weight 0.8
python politihop_scripts/dual_debiased_model_adversarial.py --constraint_loss_weight 0.007 --claim_loss_weight 0.9
python politihop_scripts/dual_debiased_model_adversarial.py --constraint_loss_weight 0.008 --claim_loss_weight 0.0
python politihop_scripts/dual_debiased_model_adversarial.py --constraint_loss_weight 0.008 --claim_loss_weight 0.1
python politihop_scripts/dual_debiased_model_adversarial.py --constraint_loss_weight 0.008 --claim_loss_weight 0.2
python politihop_scripts/dual_debiased_model_adversarial.py --constraint_loss_weight 0.008 --claim_loss_weight 0.3
python politihop_scripts/dual_debiased_model_adversarial.py --constraint_loss_weight 0.008 --claim_loss_weight 0.4
python politihop_scripts/dual_debiased_model_adversarial.py --constraint_loss_weight 0.008 --claim_loss_weight 0.5
python politihop_scripts/dual_debiased_model_adversarial.py --constraint_loss_weight 0.008 --claim_loss_weight 0.6
python politihop_scripts/dual_debiased_model_adversarial.py --constraint_loss_weight 0.008 --claim_loss_weight 0.7
python politihop_scripts/dual_debiased_model_adversarial.py --constraint_loss_weight 0.008 --claim_loss_weight 0.8
python politihop_scripts/dual_debiased_model_adversarial.py --constraint_loss_weight 0.008 --claim_loss_weight 0.9
python politihop_scripts/dual_debiased_model_adversarial.py --constraint_loss_weight 0.009 --claim_loss_weight 0.0
python politihop_scripts/dual_debiased_model_adversarial.py --constraint_loss_weight 0.009 --claim_loss_weight 0.1
python politihop_scripts/dual_debiased_model_adversarial.py --constraint_loss_weight 0.009 --claim_loss_weight 0.2
python politihop_scripts/dual_debiased_model_adversarial.py --constraint_loss_weight 0.009 --claim_loss_weight 0.3
python politihop_scripts/dual_debiased_model_adversarial.py --constraint_loss_weight 0.009 --claim_loss_weight 0.4
python politihop_scripts/dual_debiased_model_adversarial.py --constraint_loss_weight 0.009 --claim_loss_weight 0.5
python politihop_scripts/dual_debiased_model_adversarial.py --constraint_loss_weight 0.009 --claim_loss_weight 0.6
python politihop_scripts/dual_debiased_model_adversarial.py --constraint_loss_weight 0.009 --claim_loss_weight 0.7
python politihop_scripts/dual_debiased_model_adversarial.py --constraint_loss_weight 0.009 --claim_loss_weight 0.8
python politihop_scripts/dual_debiased_model_adversarial.py --constraint_loss_weight 0.009 --claim_loss_weight 0.9
