export CUDA_VISIBLE_DEVICES=6
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.0 --claim_loss_weight 0.0 --scaled_rate 0.8
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.0 --claim_loss_weight 0.0 --scaled_rate 0.9
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.0 --claim_loss_weight 0.0 --scaled_rate 1.0
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.0 --claim_loss_weight 0.0 --scaled_rate 1.1
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.0 --claim_loss_weight 0.0 --scaled_rate 1.2
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.0 --claim_loss_weight 0.1 --scaled_rate 0.8
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.0 --claim_loss_weight 0.1 --scaled_rate 0.9
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.0 --claim_loss_weight 0.1 --scaled_rate 1.0
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.0 --claim_loss_weight 0.1 --scaled_rate 1.1
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.0 --claim_loss_weight 0.1 --scaled_rate 1.2
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.0 --claim_loss_weight 0.2 --scaled_rate 0.8
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.0 --claim_loss_weight 0.2 --scaled_rate 0.9
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.0 --claim_loss_weight 0.2 --scaled_rate 1.0
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.0 --claim_loss_weight 0.2 --scaled_rate 1.1
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.0 --claim_loss_weight 0.2 --scaled_rate 1.2
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.0 --claim_loss_weight 0.3 --scaled_rate 0.8
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.0 --claim_loss_weight 0.3 --scaled_rate 0.9
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.0 --claim_loss_weight 0.3 --scaled_rate 1.0
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.0 --claim_loss_weight 0.3 --scaled_rate 1.1
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.0 --claim_loss_weight 0.3 --scaled_rate 1.2
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.0 --claim_loss_weight 0.4 --scaled_rate 0.8
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.0 --claim_loss_weight 0.4 --scaled_rate 0.9
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.0 --claim_loss_weight 0.4 --scaled_rate 1.0
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.0 --claim_loss_weight 0.4 --scaled_rate 1.1
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.0 --claim_loss_weight 0.4 --scaled_rate 1.2
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.0 --claim_loss_weight 0.5 --scaled_rate 0.8
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.0 --claim_loss_weight 0.5 --scaled_rate 0.9
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.0 --claim_loss_weight 0.5 --scaled_rate 1.0
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.0 --claim_loss_weight 0.5 --scaled_rate 1.1
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.0 --claim_loss_weight 0.5 --scaled_rate 1.2
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.0 --claim_loss_weight 0.6 --scaled_rate 0.8
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.0 --claim_loss_weight 0.6 --scaled_rate 0.9
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.0 --claim_loss_weight 0.6 --scaled_rate 1.0
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.0 --claim_loss_weight 0.6 --scaled_rate 1.1
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.0 --claim_loss_weight 0.6 --scaled_rate 1.2
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.0 --claim_loss_weight 0.7 --scaled_rate 0.8
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.0 --claim_loss_weight 0.7 --scaled_rate 0.9
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.0 --claim_loss_weight 0.7 --scaled_rate 1.0
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.0 --claim_loss_weight 0.7 --scaled_rate 1.1
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.0 --claim_loss_weight 0.7 --scaled_rate 1.2
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.0 --claim_loss_weight 0.8 --scaled_rate 0.8
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.0 --claim_loss_weight 0.8 --scaled_rate 0.9
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.0 --claim_loss_weight 0.8 --scaled_rate 1.0
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.0 --claim_loss_weight 0.8 --scaled_rate 1.1
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.0 --claim_loss_weight 0.8 --scaled_rate 1.2
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.0 --claim_loss_weight 0.9 --scaled_rate 0.8
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.0 --claim_loss_weight 0.9 --scaled_rate 0.9
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.0 --claim_loss_weight 0.9 --scaled_rate 1.0
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.0 --claim_loss_weight 0.9 --scaled_rate 1.1
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.0 --claim_loss_weight 0.9 --scaled_rate 1.2
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.001 --claim_loss_weight 0.0 --scaled_rate 0.8
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.001 --claim_loss_weight 0.0 --scaled_rate 0.9
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.001 --claim_loss_weight 0.0 --scaled_rate 1.0
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.001 --claim_loss_weight 0.0 --scaled_rate 1.1
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.001 --claim_loss_weight 0.0 --scaled_rate 1.2
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.001 --claim_loss_weight 0.1 --scaled_rate 0.8
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.001 --claim_loss_weight 0.1 --scaled_rate 0.9
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.001 --claim_loss_weight 0.1 --scaled_rate 1.0
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.001 --claim_loss_weight 0.1 --scaled_rate 1.1
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.001 --claim_loss_weight 0.1 --scaled_rate 1.2
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.001 --claim_loss_weight 0.2 --scaled_rate 0.8
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.001 --claim_loss_weight 0.2 --scaled_rate 0.9
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.001 --claim_loss_weight 0.2 --scaled_rate 1.0
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.001 --claim_loss_weight 0.2 --scaled_rate 1.1
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.001 --claim_loss_weight 0.2 --scaled_rate 1.2
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.001 --claim_loss_weight 0.3 --scaled_rate 0.8
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.001 --claim_loss_weight 0.3 --scaled_rate 0.9
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.001 --claim_loss_weight 0.3 --scaled_rate 1.0
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.001 --claim_loss_weight 0.3 --scaled_rate 1.1
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.001 --claim_loss_weight 0.3 --scaled_rate 1.2
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.001 --claim_loss_weight 0.4 --scaled_rate 0.8
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.001 --claim_loss_weight 0.4 --scaled_rate 0.9
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.001 --claim_loss_weight 0.4 --scaled_rate 1.0
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.001 --claim_loss_weight 0.4 --scaled_rate 1.1
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.001 --claim_loss_weight 0.4 --scaled_rate 1.2
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.001 --claim_loss_weight 0.5 --scaled_rate 0.8
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.001 --claim_loss_weight 0.5 --scaled_rate 0.9
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.001 --claim_loss_weight 0.5 --scaled_rate 1.0
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.001 --claim_loss_weight 0.5 --scaled_rate 1.1
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.001 --claim_loss_weight 0.5 --scaled_rate 1.2
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.001 --claim_loss_weight 0.6 --scaled_rate 0.8
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.001 --claim_loss_weight 0.6 --scaled_rate 0.9
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.001 --claim_loss_weight 0.6 --scaled_rate 1.0
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.001 --claim_loss_weight 0.6 --scaled_rate 1.1
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.001 --claim_loss_weight 0.6 --scaled_rate 1.2
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.001 --claim_loss_weight 0.7 --scaled_rate 0.8
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.001 --claim_loss_weight 0.7 --scaled_rate 0.9
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.001 --claim_loss_weight 0.7 --scaled_rate 1.0
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.001 --claim_loss_weight 0.7 --scaled_rate 1.1
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.001 --claim_loss_weight 0.7 --scaled_rate 1.2
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.001 --claim_loss_weight 0.8 --scaled_rate 0.8
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.001 --claim_loss_weight 0.8 --scaled_rate 0.9
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.001 --claim_loss_weight 0.8 --scaled_rate 1.0
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.001 --claim_loss_weight 0.8 --scaled_rate 1.1
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.001 --claim_loss_weight 0.8 --scaled_rate 1.2
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.001 --claim_loss_weight 0.9 --scaled_rate 0.8
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.001 --claim_loss_weight 0.9 --scaled_rate 0.9
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.001 --claim_loss_weight 0.9 --scaled_rate 1.0
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.001 --claim_loss_weight 0.9 --scaled_rate 1.1
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.001 --claim_loss_weight 0.9 --scaled_rate 1.2
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.002 --claim_loss_weight 0.0 --scaled_rate 0.8
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.002 --claim_loss_weight 0.0 --scaled_rate 0.9
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.002 --claim_loss_weight 0.0 --scaled_rate 1.0
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.002 --claim_loss_weight 0.0 --scaled_rate 1.1
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.002 --claim_loss_weight 0.0 --scaled_rate 1.2
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.002 --claim_loss_weight 0.1 --scaled_rate 0.8
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.002 --claim_loss_weight 0.1 --scaled_rate 0.9
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.002 --claim_loss_weight 0.1 --scaled_rate 1.0
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.002 --claim_loss_weight 0.1 --scaled_rate 1.1
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.002 --claim_loss_weight 0.1 --scaled_rate 1.2
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.002 --claim_loss_weight 0.2 --scaled_rate 0.8
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.002 --claim_loss_weight 0.2 --scaled_rate 0.9
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.002 --claim_loss_weight 0.2 --scaled_rate 1.0
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.002 --claim_loss_weight 0.2 --scaled_rate 1.1
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.002 --claim_loss_weight 0.2 --scaled_rate 1.2
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.002 --claim_loss_weight 0.3 --scaled_rate 0.8
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.002 --claim_loss_weight 0.3 --scaled_rate 0.9
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.002 --claim_loss_weight 0.3 --scaled_rate 1.0
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.002 --claim_loss_weight 0.3 --scaled_rate 1.1
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.002 --claim_loss_weight 0.3 --scaled_rate 1.2
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.002 --claim_loss_weight 0.4 --scaled_rate 0.8
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.002 --claim_loss_weight 0.4 --scaled_rate 0.9
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.002 --claim_loss_weight 0.4 --scaled_rate 1.0
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.002 --claim_loss_weight 0.4 --scaled_rate 1.1
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.002 --claim_loss_weight 0.4 --scaled_rate 1.2
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.002 --claim_loss_weight 0.5 --scaled_rate 0.8
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.002 --claim_loss_weight 0.5 --scaled_rate 0.9
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.002 --claim_loss_weight 0.5 --scaled_rate 1.0
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.002 --claim_loss_weight 0.5 --scaled_rate 1.1
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.002 --claim_loss_weight 0.5 --scaled_rate 1.2
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.002 --claim_loss_weight 0.6 --scaled_rate 0.8
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.002 --claim_loss_weight 0.6 --scaled_rate 0.9
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.002 --claim_loss_weight 0.6 --scaled_rate 1.0
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.002 --claim_loss_weight 0.6 --scaled_rate 1.1
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.002 --claim_loss_weight 0.6 --scaled_rate 1.2
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.002 --claim_loss_weight 0.7 --scaled_rate 0.8
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.002 --claim_loss_weight 0.7 --scaled_rate 0.9
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.002 --claim_loss_weight 0.7 --scaled_rate 1.0
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.002 --claim_loss_weight 0.7 --scaled_rate 1.1
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.002 --claim_loss_weight 0.7 --scaled_rate 1.2
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.002 --claim_loss_weight 0.8 --scaled_rate 0.8
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.002 --claim_loss_weight 0.8 --scaled_rate 0.9
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.002 --claim_loss_weight 0.8 --scaled_rate 1.0
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.002 --claim_loss_weight 0.8 --scaled_rate 1.1
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.002 --claim_loss_weight 0.8 --scaled_rate 1.2
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.002 --claim_loss_weight 0.9 --scaled_rate 0.8
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.002 --claim_loss_weight 0.9 --scaled_rate 0.9
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.002 --claim_loss_weight 0.9 --scaled_rate 1.0
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.002 --claim_loss_weight 0.9 --scaled_rate 1.1
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.002 --claim_loss_weight 0.9 --scaled_rate 1.2
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.003 --claim_loss_weight 0.0 --scaled_rate 0.8
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.003 --claim_loss_weight 0.0 --scaled_rate 0.9
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.003 --claim_loss_weight 0.0 --scaled_rate 1.0
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.003 --claim_loss_weight 0.0 --scaled_rate 1.1
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.003 --claim_loss_weight 0.0 --scaled_rate 1.2
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.003 --claim_loss_weight 0.1 --scaled_rate 0.8
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.003 --claim_loss_weight 0.1 --scaled_rate 0.9
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.003 --claim_loss_weight 0.1 --scaled_rate 1.0
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.003 --claim_loss_weight 0.1 --scaled_rate 1.1
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.003 --claim_loss_weight 0.1 --scaled_rate 1.2
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.003 --claim_loss_weight 0.2 --scaled_rate 0.8
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.003 --claim_loss_weight 0.2 --scaled_rate 0.9
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.003 --claim_loss_weight 0.2 --scaled_rate 1.0
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.003 --claim_loss_weight 0.2 --scaled_rate 1.1
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.003 --claim_loss_weight 0.2 --scaled_rate 1.2
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.003 --claim_loss_weight 0.3 --scaled_rate 0.8
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.003 --claim_loss_weight 0.3 --scaled_rate 0.9
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.003 --claim_loss_weight 0.3 --scaled_rate 1.0
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.003 --claim_loss_weight 0.3 --scaled_rate 1.1
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.003 --claim_loss_weight 0.3 --scaled_rate 1.2
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.003 --claim_loss_weight 0.4 --scaled_rate 0.8
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.003 --claim_loss_weight 0.4 --scaled_rate 0.9
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.003 --claim_loss_weight 0.4 --scaled_rate 1.0
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.003 --claim_loss_weight 0.4 --scaled_rate 1.1
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.003 --claim_loss_weight 0.4 --scaled_rate 1.2
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.003 --claim_loss_weight 0.5 --scaled_rate 0.8
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.003 --claim_loss_weight 0.5 --scaled_rate 0.9
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.003 --claim_loss_weight 0.5 --scaled_rate 1.0
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.003 --claim_loss_weight 0.5 --scaled_rate 1.1
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.003 --claim_loss_weight 0.5 --scaled_rate 1.2
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.003 --claim_loss_weight 0.6 --scaled_rate 0.8
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.003 --claim_loss_weight 0.6 --scaled_rate 0.9
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.003 --claim_loss_weight 0.6 --scaled_rate 1.0
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.003 --claim_loss_weight 0.6 --scaled_rate 1.1
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.003 --claim_loss_weight 0.6 --scaled_rate 1.2
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.003 --claim_loss_weight 0.7 --scaled_rate 0.8
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.003 --claim_loss_weight 0.7 --scaled_rate 0.9
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.003 --claim_loss_weight 0.7 --scaled_rate 1.0
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.003 --claim_loss_weight 0.7 --scaled_rate 1.1
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.003 --claim_loss_weight 0.7 --scaled_rate 1.2
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.003 --claim_loss_weight 0.8 --scaled_rate 0.8
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.003 --claim_loss_weight 0.8 --scaled_rate 0.9
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.003 --claim_loss_weight 0.8 --scaled_rate 1.0
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.003 --claim_loss_weight 0.8 --scaled_rate 1.1
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.003 --claim_loss_weight 0.8 --scaled_rate 1.2
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.003 --claim_loss_weight 0.9 --scaled_rate 0.8
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.003 --claim_loss_weight 0.9 --scaled_rate 0.9
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.003 --claim_loss_weight 0.9 --scaled_rate 1.0
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.003 --claim_loss_weight 0.9 --scaled_rate 1.1
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.003 --claim_loss_weight 0.9 --scaled_rate 1.2
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.004 --claim_loss_weight 0.0 --scaled_rate 0.8
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.004 --claim_loss_weight 0.0 --scaled_rate 0.9
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.004 --claim_loss_weight 0.0 --scaled_rate 1.0
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.004 --claim_loss_weight 0.0 --scaled_rate 1.1
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.004 --claim_loss_weight 0.0 --scaled_rate 1.2
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.004 --claim_loss_weight 0.1 --scaled_rate 0.8
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.004 --claim_loss_weight 0.1 --scaled_rate 0.9
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.004 --claim_loss_weight 0.1 --scaled_rate 1.0
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.004 --claim_loss_weight 0.1 --scaled_rate 1.1
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.004 --claim_loss_weight 0.1 --scaled_rate 1.2
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.004 --claim_loss_weight 0.2 --scaled_rate 0.8
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.004 --claim_loss_weight 0.2 --scaled_rate 0.9
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.004 --claim_loss_weight 0.2 --scaled_rate 1.0
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.004 --claim_loss_weight 0.2 --scaled_rate 1.1
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.004 --claim_loss_weight 0.2 --scaled_rate 1.2
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.004 --claim_loss_weight 0.3 --scaled_rate 0.8
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.004 --claim_loss_weight 0.3 --scaled_rate 0.9
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.004 --claim_loss_weight 0.3 --scaled_rate 1.0
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.004 --claim_loss_weight 0.3 --scaled_rate 1.1
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.004 --claim_loss_weight 0.3 --scaled_rate 1.2
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.004 --claim_loss_weight 0.4 --scaled_rate 0.8
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.004 --claim_loss_weight 0.4 --scaled_rate 0.9
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.004 --claim_loss_weight 0.4 --scaled_rate 1.0
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.004 --claim_loss_weight 0.4 --scaled_rate 1.1
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.004 --claim_loss_weight 0.4 --scaled_rate 1.2
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.004 --claim_loss_weight 0.5 --scaled_rate 0.8
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.004 --claim_loss_weight 0.5 --scaled_rate 0.9
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.004 --claim_loss_weight 0.5 --scaled_rate 1.0
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.004 --claim_loss_weight 0.5 --scaled_rate 1.1
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.004 --claim_loss_weight 0.5 --scaled_rate 1.2
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.004 --claim_loss_weight 0.6 --scaled_rate 0.8
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.004 --claim_loss_weight 0.6 --scaled_rate 0.9
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.004 --claim_loss_weight 0.6 --scaled_rate 1.0
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.004 --claim_loss_weight 0.6 --scaled_rate 1.1
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.004 --claim_loss_weight 0.6 --scaled_rate 1.2
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.004 --claim_loss_weight 0.7 --scaled_rate 0.8
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.004 --claim_loss_weight 0.7 --scaled_rate 0.9
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.004 --claim_loss_weight 0.7 --scaled_rate 1.0
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.004 --claim_loss_weight 0.7 --scaled_rate 1.1
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.004 --claim_loss_weight 0.7 --scaled_rate 1.2
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.004 --claim_loss_weight 0.8 --scaled_rate 0.8
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.004 --claim_loss_weight 0.8 --scaled_rate 0.9
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.004 --claim_loss_weight 0.8 --scaled_rate 1.0
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.004 --claim_loss_weight 0.8 --scaled_rate 1.1
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.004 --claim_loss_weight 0.8 --scaled_rate 1.2
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.004 --claim_loss_weight 0.9 --scaled_rate 0.8
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.004 --claim_loss_weight 0.9 --scaled_rate 0.9
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.004 --claim_loss_weight 0.9 --scaled_rate 1.0
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.004 --claim_loss_weight 0.9 --scaled_rate 1.1
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.004 --claim_loss_weight 0.9 --scaled_rate 1.2
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.005 --claim_loss_weight 0.0 --scaled_rate 0.8
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.005 --claim_loss_weight 0.0 --scaled_rate 0.9
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.005 --claim_loss_weight 0.0 --scaled_rate 1.0
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.005 --claim_loss_weight 0.0 --scaled_rate 1.1
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.005 --claim_loss_weight 0.0 --scaled_rate 1.2
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.005 --claim_loss_weight 0.1 --scaled_rate 0.8
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.005 --claim_loss_weight 0.1 --scaled_rate 0.9
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.005 --claim_loss_weight 0.1 --scaled_rate 1.0
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.005 --claim_loss_weight 0.1 --scaled_rate 1.1
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.005 --claim_loss_weight 0.1 --scaled_rate 1.2
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.005 --claim_loss_weight 0.2 --scaled_rate 0.8
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.005 --claim_loss_weight 0.2 --scaled_rate 0.9
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.005 --claim_loss_weight 0.2 --scaled_rate 1.0
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.005 --claim_loss_weight 0.2 --scaled_rate 1.1
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.005 --claim_loss_weight 0.2 --scaled_rate 1.2
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.005 --claim_loss_weight 0.3 --scaled_rate 0.8
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.005 --claim_loss_weight 0.3 --scaled_rate 0.9
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.005 --claim_loss_weight 0.3 --scaled_rate 1.0
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.005 --claim_loss_weight 0.3 --scaled_rate 1.1
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.005 --claim_loss_weight 0.3 --scaled_rate 1.2
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.005 --claim_loss_weight 0.4 --scaled_rate 0.8
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.005 --claim_loss_weight 0.4 --scaled_rate 0.9
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.005 --claim_loss_weight 0.4 --scaled_rate 1.0
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.005 --claim_loss_weight 0.4 --scaled_rate 1.1
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.005 --claim_loss_weight 0.4 --scaled_rate 1.2
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.005 --claim_loss_weight 0.5 --scaled_rate 0.8
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.005 --claim_loss_weight 0.5 --scaled_rate 0.9
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.005 --claim_loss_weight 0.5 --scaled_rate 1.0
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.005 --claim_loss_weight 0.5 --scaled_rate 1.1
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.005 --claim_loss_weight 0.5 --scaled_rate 1.2
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.005 --claim_loss_weight 0.6 --scaled_rate 0.8
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.005 --claim_loss_weight 0.6 --scaled_rate 0.9
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.005 --claim_loss_weight 0.6 --scaled_rate 1.0
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.005 --claim_loss_weight 0.6 --scaled_rate 1.1
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.005 --claim_loss_weight 0.6 --scaled_rate 1.2
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.005 --claim_loss_weight 0.7 --scaled_rate 0.8
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.005 --claim_loss_weight 0.7 --scaled_rate 0.9
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.005 --claim_loss_weight 0.7 --scaled_rate 1.0
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.005 --claim_loss_weight 0.7 --scaled_rate 1.1
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.005 --claim_loss_weight 0.7 --scaled_rate 1.2
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.005 --claim_loss_weight 0.8 --scaled_rate 0.8
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.005 --claim_loss_weight 0.8 --scaled_rate 0.9
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.005 --claim_loss_weight 0.8 --scaled_rate 1.0
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.005 --claim_loss_weight 0.8 --scaled_rate 1.1
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.005 --claim_loss_weight 0.8 --scaled_rate 1.2
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.005 --claim_loss_weight 0.9 --scaled_rate 0.8
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.005 --claim_loss_weight 0.9 --scaled_rate 0.9
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.005 --claim_loss_weight 0.9 --scaled_rate 1.0
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.005 --claim_loss_weight 0.9 --scaled_rate 1.1
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.005 --claim_loss_weight 0.9 --scaled_rate 1.2
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.006 --claim_loss_weight 0.0 --scaled_rate 0.8
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.006 --claim_loss_weight 0.0 --scaled_rate 0.9
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.006 --claim_loss_weight 0.0 --scaled_rate 1.0
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.006 --claim_loss_weight 0.0 --scaled_rate 1.1
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.006 --claim_loss_weight 0.0 --scaled_rate 1.2
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.006 --claim_loss_weight 0.1 --scaled_rate 0.8
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.006 --claim_loss_weight 0.1 --scaled_rate 0.9
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.006 --claim_loss_weight 0.1 --scaled_rate 1.0
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.006 --claim_loss_weight 0.1 --scaled_rate 1.1
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.006 --claim_loss_weight 0.1 --scaled_rate 1.2
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.006 --claim_loss_weight 0.2 --scaled_rate 0.8
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.006 --claim_loss_weight 0.2 --scaled_rate 0.9
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.006 --claim_loss_weight 0.2 --scaled_rate 1.0
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.006 --claim_loss_weight 0.2 --scaled_rate 1.1
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.006 --claim_loss_weight 0.2 --scaled_rate 1.2
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.006 --claim_loss_weight 0.3 --scaled_rate 0.8
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.006 --claim_loss_weight 0.3 --scaled_rate 0.9
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.006 --claim_loss_weight 0.3 --scaled_rate 1.0
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.006 --claim_loss_weight 0.3 --scaled_rate 1.1
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.006 --claim_loss_weight 0.3 --scaled_rate 1.2
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.006 --claim_loss_weight 0.4 --scaled_rate 0.8
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.006 --claim_loss_weight 0.4 --scaled_rate 0.9
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.006 --claim_loss_weight 0.4 --scaled_rate 1.0
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.006 --claim_loss_weight 0.4 --scaled_rate 1.1
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.006 --claim_loss_weight 0.4 --scaled_rate 1.2
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.006 --claim_loss_weight 0.5 --scaled_rate 0.8
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.006 --claim_loss_weight 0.5 --scaled_rate 0.9
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.006 --claim_loss_weight 0.5 --scaled_rate 1.0
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.006 --claim_loss_weight 0.5 --scaled_rate 1.1
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.006 --claim_loss_weight 0.5 --scaled_rate 1.2
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.006 --claim_loss_weight 0.6 --scaled_rate 0.8
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.006 --claim_loss_weight 0.6 --scaled_rate 0.9
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.006 --claim_loss_weight 0.6 --scaled_rate 1.0
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.006 --claim_loss_weight 0.6 --scaled_rate 1.1
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.006 --claim_loss_weight 0.6 --scaled_rate 1.2
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.006 --claim_loss_weight 0.7 --scaled_rate 0.8
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.006 --claim_loss_weight 0.7 --scaled_rate 0.9
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.006 --claim_loss_weight 0.7 --scaled_rate 1.0
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.006 --claim_loss_weight 0.7 --scaled_rate 1.1
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.006 --claim_loss_weight 0.7 --scaled_rate 1.2
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.006 --claim_loss_weight 0.8 --scaled_rate 0.8
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.006 --claim_loss_weight 0.8 --scaled_rate 0.9
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.006 --claim_loss_weight 0.8 --scaled_rate 1.0
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.006 --claim_loss_weight 0.8 --scaled_rate 1.1
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.006 --claim_loss_weight 0.8 --scaled_rate 1.2
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.006 --claim_loss_weight 0.9 --scaled_rate 0.8
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.006 --claim_loss_weight 0.9 --scaled_rate 0.9
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.006 --claim_loss_weight 0.9 --scaled_rate 1.0
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.006 --claim_loss_weight 0.9 --scaled_rate 1.1
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.006 --claim_loss_weight 0.9 --scaled_rate 1.2
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.007 --claim_loss_weight 0.0 --scaled_rate 0.8
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.007 --claim_loss_weight 0.0 --scaled_rate 0.9
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.007 --claim_loss_weight 0.0 --scaled_rate 1.0
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.007 --claim_loss_weight 0.0 --scaled_rate 1.1
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.007 --claim_loss_weight 0.0 --scaled_rate 1.2
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.007 --claim_loss_weight 0.1 --scaled_rate 0.8
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.007 --claim_loss_weight 0.1 --scaled_rate 0.9
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.007 --claim_loss_weight 0.1 --scaled_rate 1.0
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.007 --claim_loss_weight 0.1 --scaled_rate 1.1
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.007 --claim_loss_weight 0.1 --scaled_rate 1.2
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.007 --claim_loss_weight 0.2 --scaled_rate 0.8
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.007 --claim_loss_weight 0.2 --scaled_rate 0.9
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.007 --claim_loss_weight 0.2 --scaled_rate 1.0
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.007 --claim_loss_weight 0.2 --scaled_rate 1.1
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.007 --claim_loss_weight 0.2 --scaled_rate 1.2
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.007 --claim_loss_weight 0.3 --scaled_rate 0.8
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.007 --claim_loss_weight 0.3 --scaled_rate 0.9
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.007 --claim_loss_weight 0.3 --scaled_rate 1.0
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.007 --claim_loss_weight 0.3 --scaled_rate 1.1
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.007 --claim_loss_weight 0.3 --scaled_rate 1.2
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.007 --claim_loss_weight 0.4 --scaled_rate 0.8
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.007 --claim_loss_weight 0.4 --scaled_rate 0.9
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.007 --claim_loss_weight 0.4 --scaled_rate 1.0
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.007 --claim_loss_weight 0.4 --scaled_rate 1.1
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.007 --claim_loss_weight 0.4 --scaled_rate 1.2
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.007 --claim_loss_weight 0.5 --scaled_rate 0.8
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.007 --claim_loss_weight 0.5 --scaled_rate 0.9
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.007 --claim_loss_weight 0.5 --scaled_rate 1.0
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.007 --claim_loss_weight 0.5 --scaled_rate 1.1
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.007 --claim_loss_weight 0.5 --scaled_rate 1.2
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.007 --claim_loss_weight 0.6 --scaled_rate 0.8
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.007 --claim_loss_weight 0.6 --scaled_rate 0.9
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.007 --claim_loss_weight 0.6 --scaled_rate 1.0
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.007 --claim_loss_weight 0.6 --scaled_rate 1.1
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.007 --claim_loss_weight 0.6 --scaled_rate 1.2
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.007 --claim_loss_weight 0.7 --scaled_rate 0.8
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.007 --claim_loss_weight 0.7 --scaled_rate 0.9
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.007 --claim_loss_weight 0.7 --scaled_rate 1.0
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.007 --claim_loss_weight 0.7 --scaled_rate 1.1
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.007 --claim_loss_weight 0.7 --scaled_rate 1.2
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.007 --claim_loss_weight 0.8 --scaled_rate 0.8
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.007 --claim_loss_weight 0.8 --scaled_rate 0.9
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.007 --claim_loss_weight 0.8 --scaled_rate 1.0
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.007 --claim_loss_weight 0.8 --scaled_rate 1.1
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.007 --claim_loss_weight 0.8 --scaled_rate 1.2
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.007 --claim_loss_weight 0.9 --scaled_rate 0.8
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.007 --claim_loss_weight 0.9 --scaled_rate 0.9
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.007 --claim_loss_weight 0.9 --scaled_rate 1.0
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.007 --claim_loss_weight 0.9 --scaled_rate 1.1
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.007 --claim_loss_weight 0.9 --scaled_rate 1.2
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.008 --claim_loss_weight 0.0 --scaled_rate 0.8
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.008 --claim_loss_weight 0.0 --scaled_rate 0.9
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.008 --claim_loss_weight 0.0 --scaled_rate 1.0
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.008 --claim_loss_weight 0.0 --scaled_rate 1.1
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.008 --claim_loss_weight 0.0 --scaled_rate 1.2
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.008 --claim_loss_weight 0.1 --scaled_rate 0.8
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.008 --claim_loss_weight 0.1 --scaled_rate 0.9
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.008 --claim_loss_weight 0.1 --scaled_rate 1.0
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.008 --claim_loss_weight 0.1 --scaled_rate 1.1
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.008 --claim_loss_weight 0.1 --scaled_rate 1.2
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.008 --claim_loss_weight 0.2 --scaled_rate 0.8
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.008 --claim_loss_weight 0.2 --scaled_rate 0.9
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.008 --claim_loss_weight 0.2 --scaled_rate 1.0
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.008 --claim_loss_weight 0.2 --scaled_rate 1.1
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.008 --claim_loss_weight 0.2 --scaled_rate 1.2
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.008 --claim_loss_weight 0.3 --scaled_rate 0.8
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.008 --claim_loss_weight 0.3 --scaled_rate 0.9
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.008 --claim_loss_weight 0.3 --scaled_rate 1.0
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.008 --claim_loss_weight 0.3 --scaled_rate 1.1
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.008 --claim_loss_weight 0.3 --scaled_rate 1.2
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.008 --claim_loss_weight 0.4 --scaled_rate 0.8
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.008 --claim_loss_weight 0.4 --scaled_rate 0.9
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.008 --claim_loss_weight 0.4 --scaled_rate 1.0
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.008 --claim_loss_weight 0.4 --scaled_rate 1.1
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.008 --claim_loss_weight 0.4 --scaled_rate 1.2
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.008 --claim_loss_weight 0.5 --scaled_rate 0.8
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.008 --claim_loss_weight 0.5 --scaled_rate 0.9
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.008 --claim_loss_weight 0.5 --scaled_rate 1.0
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.008 --claim_loss_weight 0.5 --scaled_rate 1.1
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.008 --claim_loss_weight 0.5 --scaled_rate 1.2
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.008 --claim_loss_weight 0.6 --scaled_rate 0.8
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.008 --claim_loss_weight 0.6 --scaled_rate 0.9
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.008 --claim_loss_weight 0.6 --scaled_rate 1.0
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.008 --claim_loss_weight 0.6 --scaled_rate 1.1
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.008 --claim_loss_weight 0.6 --scaled_rate 1.2
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.008 --claim_loss_weight 0.7 --scaled_rate 0.8
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.008 --claim_loss_weight 0.7 --scaled_rate 0.9
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.008 --claim_loss_weight 0.7 --scaled_rate 1.0
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.008 --claim_loss_weight 0.7 --scaled_rate 1.1
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.008 --claim_loss_weight 0.7 --scaled_rate 1.2
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.008 --claim_loss_weight 0.8 --scaled_rate 0.8
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.008 --claim_loss_weight 0.8 --scaled_rate 0.9
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.008 --claim_loss_weight 0.8 --scaled_rate 1.0
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.008 --claim_loss_weight 0.8 --scaled_rate 1.1
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.008 --claim_loss_weight 0.8 --scaled_rate 1.2
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.008 --claim_loss_weight 0.9 --scaled_rate 0.8
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.008 --claim_loss_weight 0.9 --scaled_rate 0.9
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.008 --claim_loss_weight 0.9 --scaled_rate 1.0
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.008 --claim_loss_weight 0.9 --scaled_rate 1.1
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.008 --claim_loss_weight 0.9 --scaled_rate 1.2
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.009 --claim_loss_weight 0.0 --scaled_rate 0.8
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.009 --claim_loss_weight 0.0 --scaled_rate 0.9
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.009 --claim_loss_weight 0.0 --scaled_rate 1.0
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.009 --claim_loss_weight 0.0 --scaled_rate 1.1
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.009 --claim_loss_weight 0.0 --scaled_rate 1.2
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.009 --claim_loss_weight 0.1 --scaled_rate 0.8
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.009 --claim_loss_weight 0.1 --scaled_rate 0.9
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.009 --claim_loss_weight 0.1 --scaled_rate 1.0
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.009 --claim_loss_weight 0.1 --scaled_rate 1.1
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.009 --claim_loss_weight 0.1 --scaled_rate 1.2
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.009 --claim_loss_weight 0.2 --scaled_rate 0.8
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.009 --claim_loss_weight 0.2 --scaled_rate 0.9
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.009 --claim_loss_weight 0.2 --scaled_rate 1.0
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.009 --claim_loss_weight 0.2 --scaled_rate 1.1
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.009 --claim_loss_weight 0.2 --scaled_rate 1.2
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.009 --claim_loss_weight 0.3 --scaled_rate 0.8
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.009 --claim_loss_weight 0.3 --scaled_rate 0.9
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.009 --claim_loss_weight 0.3 --scaled_rate 1.0
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.009 --claim_loss_weight 0.3 --scaled_rate 1.1
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.009 --claim_loss_weight 0.3 --scaled_rate 1.2
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.009 --claim_loss_weight 0.4 --scaled_rate 0.8
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.009 --claim_loss_weight 0.4 --scaled_rate 0.9
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.009 --claim_loss_weight 0.4 --scaled_rate 1.0
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.009 --claim_loss_weight 0.4 --scaled_rate 1.1
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.009 --claim_loss_weight 0.4 --scaled_rate 1.2
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.009 --claim_loss_weight 0.5 --scaled_rate 0.8
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.009 --claim_loss_weight 0.5 --scaled_rate 0.9
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.009 --claim_loss_weight 0.5 --scaled_rate 1.0
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.009 --claim_loss_weight 0.5 --scaled_rate 1.1
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.009 --claim_loss_weight 0.5 --scaled_rate 1.2
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.009 --claim_loss_weight 0.6 --scaled_rate 0.8
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.009 --claim_loss_weight 0.6 --scaled_rate 0.9
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.009 --claim_loss_weight 0.6 --scaled_rate 1.0
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.009 --claim_loss_weight 0.6 --scaled_rate 1.1
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.009 --claim_loss_weight 0.6 --scaled_rate 1.2
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.009 --claim_loss_weight 0.7 --scaled_rate 0.8
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.009 --claim_loss_weight 0.7 --scaled_rate 0.9
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.009 --claim_loss_weight 0.7 --scaled_rate 1.0
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.009 --claim_loss_weight 0.7 --scaled_rate 1.1
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.009 --claim_loss_weight 0.7 --scaled_rate 1.2
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.009 --claim_loss_weight 0.8 --scaled_rate 0.8
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.009 --claim_loss_weight 0.8 --scaled_rate 0.9
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.009 --claim_loss_weight 0.8 --scaled_rate 1.0
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.009 --claim_loss_weight 0.8 --scaled_rate 1.1
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.009 --claim_loss_weight 0.8 --scaled_rate 1.2
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.009 --claim_loss_weight 0.9 --scaled_rate 0.8
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.009 --claim_loss_weight 0.9 --scaled_rate 0.9
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.009 --claim_loss_weight 0.9 --scaled_rate 1.0
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.009 --claim_loss_weight 0.9 --scaled_rate 1.1
python politihop_scripts/dual_debiased_model_symmetric.py --constraint_loss_weight 0.009 --claim_loss_weight 0.9 --scaled_rate 1.2
